version: "3.9"

services:
  postgres:
    image: postgres:alpine3.19
    container_name: postgres
    env_file: .env
    environment:
      POSTGRES_USER: "$DB_USER"
      POSTGRES_PASSWORD: "$DB_PASS"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

  app:
    image: local/ripe-db-search
    build: .
    container_name: app
    env_file: .env
    ports:
      - "9080:8000"
    volumes:
      - .:/code
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pgdata:
  pgadmin:
